import AsyncStorage from '@react-native-async-storage/async-storage';
import { Quiz, QuizAttempt, MistakeItem, SubjectMastery } from '../types/quiz';
import { Badge, UserStats } from '../types/achievement';
import { UserProfile } from '../types/user';

const KEYS = {
  USER_PROFILE: '@quizsmarty_user_profile',
  QUIZZES: '@quizsmarty_quizzes',
  ATTEMPTS: '@quizsmarty_attempts',
  MISTAKES: '@quizsmarty_mistakes',
  BADGES: '@quizsmarty_badges',
  USER_STATS: '@quizsmarty_stats',
  API_KEY: '@quizsmarty_gemini_api_key',
};

// Initial default user stats
export const DEFAULT_USER_STATS: UserStats = {
  totalQuizzesTaken: 0,
  totalQuestionsAnswered: 0,
  correctAnswersCount: 0,
  accuracyRate: 0,
  currentStreakDays: 1,
  bestStreakDays: 1,
  documentsUploaded: 0,
  mistakesResolved: 0,
  xp: 150,
  level: 1,
  tier: 'bronze',
};

export const DEFAULT_BADGES: Badge[] = [
  {
    id: 'badge_first_quiz',
    title: 'First Step',
    description: 'Complete your first quiz generated by AI',
    category: 'quiz_count',
    tier: 'bronze',
    iconName: 'Award',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    xpReward: 100,
  },
  {
    id: 'badge_quiz_master_5',
    title: 'Quiz Enthusiast',
    description: 'Complete 5 AI-generated quizzes',
    category: 'quiz_count',
    tier: 'bronze',
    iconName: 'BookOpen',
    unlocked: false,
    progress: 0,
    maxProgress: 5,
    xpReward: 250,
  },
  {
    id: 'badge_perfect_score',
    title: 'Flawless Victory',
    description: 'Achieve a 100% score on any quiz',
    category: 'accuracy',
    tier: 'silver',
    iconName: 'Zap',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    xpReward: 300,
  },
  {
    id: 'badge_doc_explorer',
    title: 'Scholar Uploader',
    description: 'Upload 3 study documents (PDF/PPT)',
    category: 'document_uploader',
    tier: 'bronze',
    iconName: 'FileText',
    unlocked: false,
    progress: 0,
    maxProgress: 3,
    xpReward: 150,
  },
  {
    id: 'badge_mistake_cleaner',
    title: 'Error Eraser',
    description: 'Master and resolve 5 items from the Mistake Bank',
    category: 'mistake_master',
    tier: 'silver',
    iconName: 'CheckCircle',
    unlocked: false,
    progress: 0,
    maxProgress: 5,
    xpReward: 350,
  },
  {
    id: 'badge_subject_genius',
    title: 'Grand Academician',
    description: 'Achieve over 85% mastery in any subject',
    category: 'mastery',
    tier: 'gold',
    iconName: 'Crown',
    unlocked: false,
    progress: 0,
    maxProgress: 85,
    xpReward: 500,
  },
];

export const storageService = {
  // User Profile
  async getUserProfile(): Promise<UserProfile | null> {
    try {
      const data = await AsyncStorage.getItem(KEYS.USER_PROFILE);
      return data ? JSON.parse(data) : null;
    } catch {
      return null;
    }
  },

  async saveUserProfile(profile: UserProfile): Promise<void> {
    await AsyncStorage.setItem(KEYS.USER_PROFILE, JSON.stringify(profile));
  },

  // Gemini API Key
  async getApiKey(): Promise<string | null> {
    try {
      return await AsyncStorage.getItem(KEYS.API_KEY);
    } catch {
      return null;
    }
  },

  async saveApiKey(key: string): Promise<void> {
    await AsyncStorage.setItem(KEYS.API_KEY, key);
  },

  // Quizzes
  async getQuizzes(): Promise<Quiz[]> {
    try {
      const data = await AsyncStorage.getItem(KEYS.QUIZZES);
      return data ? JSON.parse(data) : [];
    } catch {
      return [];
    }
  },

  async saveQuiz(quiz: Quiz): Promise<void> {
    const list = await this.getQuizzes();
    const updated = [quiz, ...list.filter((q) => q.id !== quiz.id)];
    await AsyncStorage.setItem(KEYS.QUIZZES, JSON.stringify(updated));
  },

  // Quiz Attempts / History
  async getAttempts(): Promise<QuizAttempt[]> {
    try {
      const data = await AsyncStorage.getItem(KEYS.ATTEMPTS);
      return data ? JSON.parse(data) : [];
    } catch {
      return [];
    }
  },

  async saveAttempt(attempt: QuizAttempt): Promise<void> {
    const list = await this.getAttempts();
    const updated = [attempt, ...list];
    await AsyncStorage.setItem(KEYS.ATTEMPTS, JSON.stringify(updated));
  },

  // Mistake Bank
  async getMistakes(): Promise<MistakeItem[]> {
    try {
      const data = await AsyncStorage.getItem(KEYS.MISTAKES);
      return data ? JSON.parse(data) : [];
    } catch {
      return [];
    }
  },

  async saveMistakes(mistakes: MistakeItem[]): Promise<void> {
    await AsyncStorage.setItem(KEYS.MISTAKES, JSON.stringify(mistakes));
  },

  async addMistake(mistake: MistakeItem): Promise<void> {
    const list = await this.getMistakes();
    // avoid duplication if same question exists and not mastered
    const exists = list.some((m) => m.question.id === mistake.question.id && !m.mastered);
    if (!exists) {
      const updated = [mistake, ...list];
      await AsyncStorage.setItem(KEYS.MISTAKES, JSON.stringify(updated));
    }
  },

  // User Stats
  async getUserStats(): Promise<UserStats> {
    try {
      const data = await AsyncStorage.getItem(KEYS.USER_STATS);
      return data ? JSON.parse(data) : DEFAULT_USER_STATS;
    } catch {
      return DEFAULT_USER_STATS;
    }
  },

  async saveUserStats(stats: UserStats): Promise<void> {
    await AsyncStorage.setItem(KEYS.USER_STATS, JSON.stringify(stats));
  },

  // Badges
  async getBadges(): Promise<Badge[]> {
    try {
      const data = await AsyncStorage.getItem(KEYS.BADGES);
      return data ? JSON.parse(data) : DEFAULT_BADGES;
    } catch {
      return DEFAULT_BADGES;
    }
  },

  async saveBadges(badges: Badge[]): Promise<void> {
    await AsyncStorage.setItem(KEYS.BADGES, JSON.stringify(badges));
  },
};
