import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const profileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bgDark,
  },
  scrollContent: {
    padding: 20,
  },
  userHero: {
    backgroundColor: colors.cardDark,
    borderRadius: 20,
    padding: 24,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.cardDarkBorder,
    marginBottom: 20,
  },
  avatarCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.cardDarkBorder,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  userName: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.textDarkPrimary,
  },
  userStatus: {
    fontSize: 13,
    color: colors.textDarkSecondary,
    marginTop: 2,
    marginBottom: 12,
  },
  tierPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 215, 0, 0.12)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  tierPillText: {
    fontSize: 11,
    fontWeight: '800',
    color: colors.tierGold,
    marginLeft: 6,
  },
  card: {
    backgroundColor: colors.cardDark,
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.cardDarkBorder,
    marginBottom: 16,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textDarkPrimary,
    marginLeft: 8,
  },
  cardDesc: {
    fontSize: 12,
    color: colors.textDarkSecondary,
    lineHeight: 18,
    marginBottom: 14,
  },
  keyInput: {
    backgroundColor: colors.bgDark,
    borderRadius: 10,
    padding: 12,
    color: colors.textDarkPrimary,
    fontSize: 14,
    borderWidth: 1,
    borderColor: colors.cardDarkBorder,
    marginBottom: 12,
  },
  saveKeyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    paddingVertical: 12,
    borderRadius: 10,
  },
  saveKeyText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFF',
    marginLeft: 6,
  },
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.2)',
  },
  logoutText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.danger,
    marginLeft: 8,
  },
});
